import type { DemoTourDefinition } from './types';

export const realEstateDemoTour: DemoTourDefinition = {
  id: 'nord-estate-sales',
  storageKey: 'nord-estate-demo-tour',
  intro: {
    title: 'Как агентство превращает Telegram-трафик в квалифицированные заявки',
    lead: 'Не каталог квартир. Воронка: квалификация → подбор → намерение → просмотр → HOT lead в CRM.',
    bullets: [
      'Клиент отвечает на 8 коротких шагов',
      'Движок объясняет, почему объекты подходят',
      'Менеджер видит score, timeline и готовность к сделке',
    ],
    startLabel: 'Показать сценарий',
    skipLabel: 'Смотреть самостоятельно',
  },
  finish: {
    title: 'От рекламы до CRM-handoff',
    lead: 'Человек пришёл из рекламы. Mini App выяснил потребность, подобрал объекты, увидел намерение и отдал менеджеру HOT lead.',
    bullets: [
      'Qualification без менеджера',
      'Deterministic matching + reasons',
      'Behavioral scoring',
      'Просмотр только после явного подтверждения',
      'CRM-ready payload',
    ],
    adminLabel: 'Открыть кабинет менеджера',
    continueLabel: 'Остаться в приложении',
  },
  steps: [
    {
      id: 'home',
      target: 'home-cta',
      route: '/',
      title: 'Точка входа',
      description: 'Главный CTA — «Подобрать квартиру». Не бесконечный каталог, а квалификация покупателя.',
    },
    {
      id: 'qualify',
      target: 'qualify-step',
      route: '/qualify',
      action: 'fill-qualification',
      title: 'Квалификация',
      description: 'Цель, район, бюджет, комнаты, срок и способ оплаты. Профиль сохраняется только после согласия.',
    },
    {
      id: 'matches',
      target: 'matches-list',
      route: '/matches',
      action: 'open-matches',
      title: 'Персональный подбор',
      description: 'Объекты ранжируются детерминированным score. Лучшие — сверху, с объяснением.',
    },
    {
      id: 'property',
      target: 'match-reasons',
      route: '/properties/preview',
      action: 'open-property',
      title: 'Почему подходит',
      description: '92% — не магия. Бюджет, район, комнаты, отделка. Расчёт платежа и избранное — сигналы намерения.',
    },
    {
      id: 'favorite',
      target: 'favorite-btn',
      title: 'Сигнал интереса',
      description: 'Избранное не просто «сердечко». Это +7 к lead score. Тур его не создаёт — только пользователь.',
    },
    {
      id: 'viewing',
      target: 'viewing-confirm',
      route: '/properties/preview/viewing',
      action: 'open-viewing',
      title: 'Запись на просмотр',
      description: 'Дата, слот, формат. Запись появится только после кнопки «Подтвердить».',
    },
    {
      id: 'lead',
      target: 'lead-score',
      route: '/demo/admin/leads',
      action: 'open-admin-lead',
      title: 'Карточка лида',
      description: 'Мария Соколова — HOT. Менеджер видит требования, финансы, избранное и timeline.',
    },
    {
      id: 'score',
      target: 'lead-timeline',
      title: 'Почему HOT',
      description: 'Score складывается из профиля и поведения. Каждое изменение записано в LeadScoreEvent.',
    },
    {
      id: 'analytics',
      target: 'funnel-chart',
      route: '/demo/admin/analytics',
      action: 'open-analytics',
      title: 'Воронка',
      description: 'App opened → qualification → viewed → favorite → viewing. Считается по first-party событиям.',
    },
    {
      id: 'crm',
      target: 'crm-ready',
      title: 'CRM-ready',
      description: 'Handoff: клиент, профиль, score, matches, favorites, viewing, UTM. Application layer не знает Bitrix.',
    },
  ],
};
